### ISSUE TITLE
Any plans to extend the Card component?

### ISSUE THREAD

**Issue by justmelnyc** [zeit-ui/react#120]
# Feature request 🚀

### Expected:
  - No breaking changes

### Examples:
```js
```

### Others:
Like Card.Footer or Card.Actions?, to create cards like on the zeit (Vercel?) website.

<img width="673" alt="ss 2020-04-21 at 12 55 53 PM" src="https://user-images.githubusercontent.com/10662231/79895092-5a544900-83d4-11ea-8d13-fb873963c6f7.png">

**Comment by unix** [comment]
Good point, I want these too.
I'll remind you when I finish it.

**Comment by justmelnyc** [comment]
Thank you so much. I really appreciate your work on this.

**Comment by unix** [comment]
@justmelnyc 
You can check the feature progress here: #121 .  And a new pre-release version will be generated when PR is merged.
