### ISSUE TITLE
adjust modal styles for dark mode

### ISSUE THREAD

**Issue by justmelnyc** [zeit-ui/react#125]
# About `styles` 🛠️

in dark mode the modal overly color is off. 
<img width="1241" alt="ss 2020-04-23 at 12 26 02 PM" src="https://user-images.githubusercontent.com/10662231/80124219-ee9de780-855d-11ea-9861-38669164e4fd.png">

can we make it darker to fit the zeit design. 
<img width="1151" alt="ss 2020-04-23 at 12 25 02 PM" src="https://user-images.githubusercontent.com/10662231/80123908-7f27f800-855d-11ea-9d69-4be5b3b20fc1.png">

and also can we change the heading and subheading to title case?

**Comment by unix** [comment]
Fixed in #127 .
The new version will be released later.
