### ISSUE TITLE
Change of name from ZEIT

### ISSUE THREAD

**Issue by nocategory** [zeit-ui/react#126]
Since ZEIT recently changed their name to Vercel ([https://vercel.com/blog/zeit-is-now-vercel](https://vercel.com/blog/zeit-is-now-vercel)) would it maybe make some sense to change things around here (not only react, but vue and others as well)?

Or just not worth it and you'll keep everything the same? Just wanna be sure since you could change the package name as well (probably wouldn't happen) but yeah...

**Comment by unix** [comment]
Thanks.
Changing the package name means that many projects need to be migrated, I want to keep the package name temporarily. (secretly tell you, I registered the organization name of `vercel-ui` in npm 😿)

**Comment by unix** [comment]
🤔I thought for a while, maybe we need to change the document at latest.

**Comment by unix** [comment]
I changed the reference name of the document in PR #135.
If anyone  finds the text to be modified, please edit the document at any time.
