### ISSUE TITLE
从unix过来，希望改进一些markdonw的默认样式

### ISSUE THREAD

**Issue by MeCKodo** [zeit-ui/react#142]
# About `styles` 🛠️

![image](https://user-images.githubusercontent.com/10184444/80353623-313a2980-88a8-11ea-8b20-f629bc42e4fb.png)

**Comment by unix** [comment]
收到。
关于引用：这个样式会在 `CSSBaseline` 中追加。
关于列表：这个样式暂时不会更改，这是 `zeit-design` 的固定设计。如果你想要覆盖它非常简单，只需要在 `pages/_app.jsx` 内部增加 `styles`，或是自己写一个全局的样式引入即可。

**Comment by unix** [comment]
在 #143 添加 `blockquote` 支持。
