### ISSUE TITLE
How can we get Fieldset sections like on Vercel site, with divider and labels.

### ISSUE THREAD

**Issue by justmelnyc** [zeit-ui/react#146]
# About `styles` 🛠️

<img width="611" alt="ss 2020-04-28 at 10 39 49 AM" src="https://user-images.githubusercontent.com/10662231/80500913-cab31b00-893c-11ea-9b13-ff9371af07c9.png">

**Comment by unix** [comment]
This part is hard to abstract, I suggest simulating with `Card`:

```jsx
<Card>
  something
  <Divider />
  something
</Card>
```

But, the `Divider` component is constrained by padding of `Card`:

<img width="119" alt="card" src="https://user-images.githubusercontent.com/11304944/80505158-8ceadc80-89a6-11ea-85f4-2d7355a8d5e9.png">

I thought for a moment, to solve this problem, this only way is to pack content of a new component `Card.Conent`:

```jsx
<Card>
 <Card.Content>something</Card.Content>
  <Divider />
  <Card.Content>something</Card.Content>
</Card>
```

I think it's good solution, what's your opinion? 
The component `Card` will automatically identify sub component `Card.Content`, if you do not need `Card.Content`, you don't need to do anything,  just use it as before.

----

About labels, currently only `Text` component provides text rendering.
Now there are not enough designs for the labels, so we can't provide components similar to `Label` / `Title` / `Subtitle`.

```jsx
<Text type="secondary" styles={{ textTransform: 'uppercase', fontSize: 20 }}>
    Select Acoount
</Text>
```

But I guess it look better, right? (`font-size` can be one of the parameters)

```jsx
<Text size={20} styles={{ color: '#000' }}>
    Select Acoount
</Text>
<Text type="secondary" size={20} styles={{ textTransform: 'uppercase' }}>
    Select Acoount
</Text>
```

**Comment by unix** [comment]
@ofekashery What do you think of this feature?

**Comment by ofekashery** [comment]
It can be done with something like this:
https://codesandbox.io/s/vercel-design-fieldset-14gpl?file=/src/App.js
```tsx
<Fieldset style={{ width: 400 }}>
  <Fieldset.Title>Import Next.js Template</Fieldset.Title>
  
  <Divider style={{ margin: "16pt -16pt", maxWidth: "unset" }} />
  
  <Description title="Select Account" />
  <Row align="middle">
    <Col span={12}>
      <User
        src="https://zeit.co/api/www/avatar/?u=evilrabbit&s=160"
        name="Evil Rabbit"
        style={{ padding: 0 }}
      />
    </Col>
    <Col>
      <Popover content={<Users />}>
        <Chevron size={14} />
      </Popover>
    </Col>
  </Row>
  
  <Divider style={{ margin: "16pt -16pt", maxWidth: "unset" }} />
  
  <Description title="Project Name" />
  <Input placeholder="My React App" width="100%" />

  <Fieldset.Footer>
    <Fieldset.Footer.Status>From vercel/now</Fieldset.Footer.Status>
    <Fieldset.Footer.Actions>
      <Button auto size="mini">
        Actions
      </Button>
    </Fieldset.Footer.Actions>
  </Fieldset.Footer>
```

![image](https://user-images.githubusercontent.com/16443111/80509721-72067100-8982-11ea-8eab-d0da68eefe87.png)

**Comment by justmelnyc** [comment]
@unix Yea I tried using the Divider, but as you mentioned the padding is an issue.
 
I like the Card.Content option to go along with Footer, and any future features like Card.Header etc. for example the Verel Design Guide has a VideoCard which adds a play Icon in the center of the image.

**Comment by unix** [comment]
@justmelnyc 
If you want to use `Fieldset`, an example written by *ofekashery* can be used as a reference.
If you want to use `Card`, you need to wait for me to finish this feature.

@ofekashery 
I'm so surprised that you finished the example in such a short time! 👍

**Comment by justmelnyc** [comment]
@unix I replied right before @ofekashery submitted that example, I'm ok using the `Fieldset`. thank you both.

**Comment by unix** [comment]
@justmelnyc 
Update, now both `Fieldset` and `Card` support `Content`.
If someone else has the same problem, here's a [new example](https://react.zeit-ui.co/en-us/components/fieldset#with-divider) for `Divider` and `Fieldset`.
