### ISSUE TITLE
Input autofill text color and background are both black in dark mode.

### ISSUE THREAD

**Issue by justmelnyc** [zeit-ui/react#150]
# Bug report 🐞
The input autofill text color is black as well as the background, in dark mode.

## Actual results (or Errors)
<img width="387" alt="ss 2020-04-28 at 10 47 10 PM" src="https://user-images.githubusercontent.com/10662231/80556789-bd307c00-89a2-11ea-9e44-21fbadab7875.png">

**Comment by unix** [comment]
Fixed in #151 , released `1.0.0-rc.7`.
