### ISSUE TITLE
Note filled variant text color 

### ISSUE THREAD

**Issue by justmelnyc** [zeit-ui/react#154]
# About `styles` 🛠️

In Vercel the filled Note text color is white.
<img width="540" alt="ss 2020-04-28 at 10 46 23 PM" src="https://user-images.githubusercontent.com/10662231/80611902-3ebaf500-8a09-11ea-912a-d5974ee7922f.png">

<img width="387" alt="ss 2020-04-28 at 10 47 10 PM" src="https://user-images.githubusercontent.com/10662231/80612054-6f9b2a00-8a09-11ea-874c-a7b8235a99fe.png">

**Comment by unix** [comment]
Thank you for feedback. I will solve it ASAP.

**Comment by justmelnyc** [comment]
Thank you for all the work that you do.
