### ISSUE TITLE
Avatar with Icon

### ISSUE THREAD

**Issue by justmelnyc** [zeit-ui/react#156]
# Feature request 🚀
option to add Icon (badge) to Avatar Component.

<img width="251" alt="ss 2020-04-29 at 7 13 37 PM" src="https://user-images.githubusercontent.com/10662231/80655984-0be72000-8a4e-11ea-8c5c-90d8bf04b7f1.png">
<img width="272" alt="ss 2020-04-29 at 7 17 27 PM" src="https://user-images.githubusercontent.com/10662231/80655996-15708800-8a4e-11ea-93a5-35196d13d725.png">

### Expected:
  - No breaking changes

### Examples:
```js
```

**Comment by unix** [comment]
I tried to implement this feature，however,  the styles(`bgColor, color, border-color, dark-mode...`) of icon and avatar can't be well combined. 
The ZEIT's example is just a special case, the design of superimposed images is very poor in the general scenes. At present, this design style can not be used as a component library.

The component library needs to consider more marginalized cases, ensure availability in more scenes. So, currently, this feature will not be considered, unless the design is improved.

**Comment by unix** [comment]
Well, I think Badge is a good idea. I'll implement automatic composition of Badge component in several components later.
For more details, I will come back after PR creation. And thank you for your feedback to make us better.

**Comment by unix** [comment]
Now you can add `Badge` to `Avatar`, preview [here](https://react-kgkrmdini.now.sh/en-us/components/badge#anchor).

But the feature of combination `SVG / Image` and `Avatar` will not added temporarily, if you need this function, please refer to the follow codes:

```jsx
() => {
    return (
      <div className="box">
        <Avatar />
        <img src="" className="team" />
        <style jsx>{`
          .box {
            position: relative;
          }
          
          .team {
            position: absolute;
            bottom: 0;
            right: 0;
          }
        `}</style>
      </div>
    )
  }
```
