### ISSUE TITLE
Any way to be project sponsor?

### ISSUE THREAD

**Issue by oif** [zeit-ui/react#159]
(this is not a real feature request, so I deleted the template)

This is a gorgeous UI Kit and I had used it in our project. So is there any way to be a project sponsor?
Taking my meager power to make the project more briskly.

**Comment by unix** [comment]
Thank you very much 🤒 
The project has not yet started Sponsorships plan. (you can also sponsor me on my GitHub panel if you like) 
This is not the most important thing. To continue to use `zeit-ui` is the greatest support for the project. However, thank you for your message, let's make it better together. 🥂
