### ISSUE TITLE
Card hover state and Icon

### ISSUE THREAD

**Issue by justmelnyc** [zeit-ui/react#163]
# Feature request 🚀
Vercel <Cards/> have a hover state and a <VideoCard/> variant

<img width="639" alt="ss 2020-05-01 at 12 46 41 PM" src="https://user-images.githubusercontent.com/10662231/80825036-9befab80-8bad-11ea-8c45-75c5edb96f69.png">

1. thicker white border and slightly elevated on hover. 
2. a centered play <Icon/> over <Image/>, 

any of these features would be greatly appreciated.

### Expected:
  - No breaking changes

### Examples:
```js
```

**Comment by unix** [comment]
All of these belong to `VideoCard`, but I don't have a good plan for this component.
The `VideoCard` maybe added in the future, but I can't promise  a definite date, my recent work is util functions and documentation. 
Or you can try to contribute to a component, here are many component examples for reference. Let me know if you have any ideas.

**Comment by justmelnyc** [comment]
Yea I would love to help, is there a guideline we can reference? I want to adhere to your style guide.

**Comment by unix** [comment]
@justmelnyc 
I update contributing guide on #164 , these documents should helo you.

**Comment by justmelnyc** [comment]
Thanks.

**Comment by unix** [comment]
I close the issue because there was no active discussion.
Any updates or questions, reopen it.
