### ISSUE TITLE
Component Select doesn't display correctly in Modal

### ISSUE THREAD

**Issue by stivaugoin** [zeit-ui/react#165]
# Bug report 🐞
When I use `Select` in `Modal` I don't see the options because the z-index of class `dropdown` is `100` and the z-index of the modal is `1001`.

I can help if you want and accept PR.

## Version & Environment
`1.0.0-rc.8`

## Expection
![image](https://user-images.githubusercontent.com/1130466/80845070-2e0baa00-8bd6-11ea-842c-eb519371dcb8.png)

![image](https://user-images.githubusercontent.com/1130466/80845250-b0946980-8bd6-11ea-9866-73cf03f7fe98.png)

## Actual results (or Errors)
![image](https://user-images.githubusercontent.com/1130466/80845024-0b799100-8bd6-11ea-83d5-9371cc07a473.png)

![image](https://user-images.githubusercontent.com/1130466/80845186-88a50600-8bd6-11ea-8f31-dbf9dead3bb9.png)

**Comment by unix** [comment]
You can create PR at any time, here are some helpful [guidelines](https://github.com/zeit-ui/react/blob/master/.github/CONTRIBUTING.md).

**Comment by unix** [comment]
Since I haven't received your reply or PullRequest, I fixed this issue in #167 .

**Comment by stivaugoin** [comment]
Thanks @unix 💪
