### ISSUE TITLE
Effect property on Button component

### ISSUE THREAD

**Issue by RubenZx** [zeit-ui/react#171]
# About `styles` 🛠️
I have a problem setting this property to false, because the effect doesn't change.
If i'm not wrong, that property should change the effect on hover on the button component, and it will have no effect by setting to false.

### Code: 
```
<Button size="small" type="success" ghost effect={false}>
  MyButton
</Button>
```

### Result
![The button](https://media.giphy.com/media/Ti0sUlwATEI88voMUk/giphy.gif)

**Comment by unix** [comment]
Uh huh, yeah, the `effect` prop does not change the `hover` effect.

When the normal `Button` components are clicked, they will have animation effect like water waves. Prop `effect` is used of turn off the animation effect.
There's a little difference here, **If the `Button` component is in special mode (`ghost` / `loading` / `disabled` ...),  the animation is disabled.**

**Comment by unix** [comment]
I don't know if you noticed, If `Button` component has `shadow` prop, the `hover` effect  is disabled. 
If you just want to disable `hover` effect, this style (`shadow`) may help you?

**Comment by RubenZx** [comment]
Thanks for the explanation. I wanted the same that happens on `shadow` style, but without the shadow effect. I mean, i want a `ghost` button, but without any hover effect. I don't know if that is supported.

**Comment by unix** [comment]
Currently, there is no plan to support disable some styles, but as an alternative, you can customize a `Button` component to implement this style.
I have an online  [example on codesendbox](https://codesandbox.io/s/custom-button-without-hover-495nn?file=/src/App.js) for you, Is this what you need?

**Comment by RubenZx** [comment]
Yeah, that's the best alternative, thank u so much! 😊
