### ISSUE TITLE
A general Page layout

### ISSUE THREAD

**Issue by unix** [zeit-ui/react#172]
# Feature request 🚀

I'll rewrite the `layout` component everytime I create a project (especially in the `next.js` project),
can we provider `Page` component to improve the experience?
The component `Page` has some useful parameters to reduce repetitive code:

```
<Page size="large">{content}</Page>  // width: 1000pt
<Page size="small">{content}</Page>  // width: 700pt

<Page meta={meta}>{content}</Page> 
<Page footer={Footer}>{content}</Page>

...others
```

## Expected

  - set `width` / `height` / other styles
  - set the meta in head automatically
  - adjust width at breakpoint
  - render after effect triggered
  - render after effect triggered, but keep the html string and hide it for SEO

## Others

This component doesn't seem to be universal, but I really want use it 😄. maybe we need to create
a new repo to manage these components? (`Page` / `Sidebar` / `Sharer` ...)

I'd like to hear from your views 👀

**Comment by justmelnyc** [comment]
Yes I love this Idea. We do need a way to manage page styles that’s consistent
