### ISSUE TITLE
[Select] enable native option on mobile device

### ISSUE THREAD

**Issue by unix** [zeit-ui/react#177]
# Feature request 🚀

We simulated the `option` element in `@zeit-ui/react`, because the browser's `option` is the system interface called, and the style can't be modified. But simulation elements don't wokr best on mobile devices:

- **Native in browser:**
<img width="267" alt="select-1" src="https://user-images.githubusercontent.com/11304944/81274146-7d445580-9082-11ea-83de-5c0d17c6d840.png">

- **`@zeit-ui/react` in browser:**

<img width="244" alt="select-2" src="https://user-images.githubusercontent.com/11304944/81274208-8e8d6200-9082-11ea-92ef-55a4ed1b5e59.png">

- **Native on mobile devices:**

<img width="449" alt="select-3" src="https://user-images.githubusercontent.com/11304944/81274289-a95fd680-9082-11ea-8a36-8b88eab25a91.png">

**Better user experience with native `option` on mobile devices.**

### Expected:
  - Simulate `option` in browser, and use native `option` on mobile devices.
  - Users don't have to do anything.

### Others:

Cannot render if the `Option` contains components:

```jsx
<Select.Option value="1"><Code>TypeScript</Code></Select.Option>
```

**Comment by unix** [comment]
Maybe this function is not needed, because `@zeit-ui/react` is not a mobile ui lib and does not need to be optimize too much?

**Comment by justmelnyc** [comment]
In mobile, I noticed Vercel uses the Drawer component, its a variant of the Modal. but adding mobile/responsive features can only be a good thing, in my opinion.

**Comment by unix** [comment]
@justmelnyc 
Yes, responsive is what we need. I've thought about it before, it looks like a big job.

We need some components and hooks  to solve the responsive layout, like `Hidden` / `useMediaQuery` etc. Later, I will list a milestone with responsive features.

**Comment by telmogoncalves** [comment]
Any plans to make the `grid` responsive as well?

**Comment by unix** [comment]
@telmogoncalves 
I also want component like fluid grid. I plan to add a new component called `Grid`, it work in a similar way to material grid.

**Comment by justmelnyc** [comment]
@unix we’re on the same page, all the time.

**Comment by unix** [comment]
I will colse it. Let's wait until we have the responsive layout to consider this issue.
