### ISSUE TITLE
Cannot pass reference to input

### ISSUE THREAD

**Issue by RubenZx** [zeit-ui/react#189]
# Bug report 🐞

## Expection
I want to use the `ref` attribute of the `Input` component to use with `react-hooks-form`, but i cannot pass the reference.

## Actual results (or Errors)
```
<Input width="100%" name="email" ref={register} />
```

**Comment by unix** [comment]
`Input` is forward `Ref` by default. I cerated an exampel [here](https://codesandbox.io/s/zeit-ui-react-input-ref-eqefe?file=/src/app.js) and not found any issue. 

Would you mind sharing more information about this error? (version / behavior / alert messages / online example)

**Comment by RubenZx** [comment]
Ok,

**Comment by RubenZx** [comment]
I'm using the react+typescript with the latest version, `@zeit-ui/react: 1.2.0-rc.0`, and `react-hook-form: 5.6.3`. And when I try to use the `ref` attribute (I also try to use `itemRef`) I got the following:

<img width="1141" alt="Screen Shot 2020-05-09 at 00 04 33" src="https://user-images.githubusercontent.com/36533775/81452970-abac5880-9188-11ea-9ecf-bd7a21ad61f9.png">

**Comment by unix** [comment]
Thank for you feedback, this is a type issue of forward function, I fixed it here: #190 .
