### ISSUE TITLE
add button group

### ISSUE THREAD

**Issue by justmelnyc** [zeit-ui/react#193]
add button group option for Button Component. 

could be used as a switch or for pagination.

Vercel has a Swith Component with the following API.

`<Switch
        items={[
          {
            name: 'Source',
            value: 'source',
            width: 80
          },
          {
            name: 'Output',
            value: 'output',
            width: 90
          }
        ]}
        active={active}
        onChange={v => setActive(v)}
      />`

<img width="297" alt="ss 2020-05-01 at 1 18 04 PM" src="https://user-images.githubusercontent.com/10662231/81474489-c1933b00-91d3-11ea-857c-c85bfdcb23ed.png">
# Feature request 🚀

### Expected:
  - No breaking changes

### Examples:
```js
```

**Comment by unix** [comment]
### About `ButtonGroup`

First of all, I think `ButtonGroup` is necessary, this component is really useful, but it can't be replaced as `Pagination`. Second, Vercel's `Swtich` component is not practical, it's too limited.

I will add `ButtonGroup` component, but I will folllow a few points:

  - Refer to the design of `Switch`, but not all. The `Button` have multiple states to consider.
  - To keep the buttons consistent, I will disable some props in group, like `ghost` / `shadow` etc.

Maybe they looke like this:

```jsx
<Button.Group disabled  type size>
  <Button>Action1</Button>
  <Button>Action2</Button>
</Button.Group>
```

----

### About `Pagination`

Besides, I don't have any plans for component `Pagination` at the moment, If the `ButtonGroup` component does well, (I mean, it's just reference to design, **but we create  new component**.) I will make a  feature request to add `Pagination` component (not now). 


----

### About Feature

Thank you for your suggestion agian, you showed us what users need. However, it it recommended that you improve the issue message or follow us issue template. **It's not about helping me, it's about showing it to everyone in the community.**

**Comment by unix** [comment]
BTW: Now I'm working on `Grid` component, anyone with an opinon can leave a message, and if you want to take this feature, let me know.
