### ISSUE TITLE
Cannot use a form inside a modal

### ISSUE THREAD

**Issue by RubenZx** [zeit-ui/react#195]
# Bug report 🐞

I cannot create a `form` inside a `modal`, I've made outside of the `modal` and works well, but when I try to create it as the content of a `modal`, cannot submit. Here is a [codesandbox](https://codesandbox.io/s/modal-form-rqweq) of the problem.

**Comment by unix** [comment]
Currently you can use [ref](https://codesandbox.io/s/modal-form-ref-pbw7u?file=/src/App.tsx) to solve this issue, it works in all browsers. Of course, I'm still looking for a better solution. I'll remind you of any updates here.

**Comment by unix** [comment]
@RubenZx 
This issue has been fixed, the patch version will be released later.

**Comment by belhassen07** [comment]
> @RubenZx
> This issue has been fixed, the patch version will be released later.

Hey is the patch released yet?

**Comment by unix** [comment]
@belhassen07 
This patch is released in version [v1.2.1](https://github.com/zeit-ui/react/releases/tag/v1.2.1). Is this issue repeated alain?
please open a new issue if you have any questions.
