### ISSUE TITLE
Broken vertical align in button dropdowns

### ISSUE THREAD

**Issue by Bant89** [zeit-ui/react#21]
# About `styles` 🛠️

Hi, first of all thanks for all the work done will keep in mind this for future projects =)

Just wanted to share that on Firefox 72 in Ubuntu the vertical alignment in the main item of the dropdown doesn't work as expected the text is align too close to the top.

![image](https://user-images.githubusercontent.com/27152632/77648189-1d647600-6f3e-11ea-8301-3c2c0e292f50.png)
![image](https://user-images.githubusercontent.com/27152632/77648333-5ef52100-6f3e-11ea-9a37-b0d3c8f22179.png)
![image](https://user-images.githubusercontent.com/27152632/77648369-6d433d00-6f3e-11ea-8ead-a324aada886f.png)

A change that may fix this is adding in _components/button-dropdown/item.tsx_ on the style jsx of the button.
```css
align-items: center;
```
I have only tested it on Firefox/Chrome if the change is made please confirm with other browsers.

**Comment by itshaydendev** [comment]
```css
.button {
  display: flex;
  align-items: center;
}
```
That should fix it, I agree with @Bant89

**Comment by unix** [comment]
Thanks you for your feedback, I'll fix it ASAP.
