### ISSUE TITLE
Input iconRight bug

### ISSUE THREAD

**Issue by battall** [zeit-ui/react#213]
# Bug report 🐞

## Version & Environment
@zeit-ui/^1.5.0-rc.2

Browser: Firefox (works fine on chrome)

## Expection
expecting icon to be inside of input when setting width, but it is not.

## Actual results (or Errors)
default width;
![image](https://user-images.githubusercontent.com/50958739/82119451-56270b80-9787-11ea-8cb1-dcd25e5f094d.png)

width set to 200px;
![image](https://user-images.githubusercontent.com/50958739/82119427-2972f400-9787-11ea-9905-f7d58632866a.png)

**Comment by battall** [comment]
Just looked to chrome, it works on there. don't works on firefox.

**Comment by unix** [comment]
Thank you for your report, fixed in #214 .
Stable version(`v1.4.4`) and pre-release version(`v1.5.0-rc.3`) will be out later.
