### ISSUE TITLE
Refs are not being passed or not typed?

### ISSUE THREAD

**Issue by PaulPCIO** [zeit-ui/react#219]
## Expection
The ref to be forwarded to the components, eg a button:
![image](https://user-images.githubusercontent.com/39598117/82492788-13e32e80-9ae7-11ea-89a9-437ed35d3f75.png)

**Comment by PaulPCIO** [comment]
![image](https://user-images.githubusercontent.com/39598117/82493067-a1268300-9ae7-11ea-82b7-211e2b7806b3.png)

**Comment by unix** [comment]
The `Button` component does not support `forward`, the following components support `forward`:
  - `Input`
  - `Text`
  - `Link`

What functions do you need `Ref` to solve? Would you mind sharing what you want to do?

**Comment by PaulPCIO** [comment]
So my current workaround is to un-type the onClick prop but that also means I can not take advantage of the onClick event

The reason that I would like to use the ref is to be able to systematically trigger a button click allowing the onClick to keep its event source.

here is an example where I would like to trigger the button click using "Enter" keypress

```tsx
export default function EnterButton(props: EnterButtonProps) {
  const buttonRef = useRef<HTMLButtonElement>(null)

  const onClick: ButtonProps['onClick'] = (e) => {
    console.log(e)
  }

  useEffect(() => {
    const handleClick = ({ keyCode }: KeyboardEvent) => {
      // ❌ manually running the onClick function (as you can see the event will be missing in this onClick function)
      if (keyCode === 13 && onClick) onClick()
      // ✅ i want to systematically trigger the button click to allow for its event to be passed to the target
      if (keyCode === 13 && buttonRef.current) buttonRef.current.click()
    }
    if (process.browser) window.addEventListener('keypress', handleClick, false)
    return () => {
      if (process.browser) window.removeEventListener('keypress', handleClick, false)
    }
  }, [onClick])

  return (
    <>
      <button ref={buttonRef} onClick={onClick}>
        Test
      </button>
      <Button type="secondary" onClick={onClick}>
        Test
      </Button>
    </>
  )
}
```

**Comment by unix** [comment]
This is really one of the usage scenarios, I will add `forwardRef` for `Button` component. You can try it  out in `1.6.0-canary.0`.(It will be released later)

BTW, if you use `Button` component in the `form` element, pressing `enter` (keyCode === 13) will automatically trigger the `submit` event:

```jsx
<form onSubmit={() => console.log('submit')}>
  <Button htmlType="submit">Action</Button>
</form>
```
