### ISSUE TITLE
Dedicated navbar component?

### ISSUE THREAD

**Issue by itshaydendev** [zeit-ui/react#22]
# Feature request 🚀

Make a navbar like Zeit's
![image](https://user-images.githubusercontent.com/22327045/77665280-5b31c080-6f77-11ea-9483-f7c36b799540.png)
![image](https://user-images.githubusercontent.com/22327045/77665318-65ec5580-6f77-11ea-9d20-faacb4fc4ae0.png)

**Comment by unix** [comment]
This is a composite implementation of multiple components, I don't think it's a single component, this can cause too much complexity for a single component.

**As a solution**, we can have a best practice project template, like `zeit-ui/react-best-admin`, we can use another repo to show the best way to use composite components.

**Comment by unix** [comment]
Update, Here is a good example project: [zeit-dashboard-template](https://github.com/ofekashery/zeit-dashboard-template).
