### ISSUE TITLE
Input ref updates

### ISSUE THREAD

**Issue by PaulPCIO** [zeit-ui/react#224]
# Bug report 🐞

## Version & Environment
@zeit-ui/react: `1.6.0-canary.0`

## Expectation
Using the ref to update the input component should work the same as a standard input component, an example would be to use the input with `react-hook-form` that takes advantage of the components refs.

## Actual results (or Errors)
The component does not seem to trigger value changes. here is an example

https://codesandbox.io/s/zeit-ui-input-refs-2fx24

**Comment by unix** [comment]
This is not an issue from `zeit-ui/react`.

Docuemnts for handling controlled components using `react-hook-from` [here](https://react-hook-form.com/api/#Controller). this is an [online example](https://codesandbox.io/s/zeit-ui-input-react-hook-form-leu38) for reference.

**Comment by PaulPCIO** [comment]
So reactive 💯love it 👍thanks @unix missed that.
