### ISSUE TITLE
question about browser compatibility

### ISSUE THREAD

**Issue by zctocm** [zeit-ui/react#226]
# About `docs`

What about browser compatibility?

I think you can add a description of browser compatibility to the doc.

Thanks

**Comment by PaulPCIO** [comment]
I actually was just wondering the same thing, I tried accessing the docs on Microsoft Edge which do not seem to work, also tried modal within my app which also does not seem to be supported

![image](https://user-images.githubusercontent.com/39598117/82652712-5b200b00-9c1e-11ea-8db1-b4874508c8c0.png)

**Comment by PaulPCIO** [comment]
Note that I think i have an old version of edge in my virtual machine, I'm going to try to update and try other browsers as well.

**Comment by unix** [comment]
@zctocm 
Thank you for pointing this out, we do lack a compatibility list now. 

@PaulPCIO 
Great work 👍 , your message is very helpful to everyone.

**For everyone:**
We will add a docuemnt to show the compatibility of `zeit-ui/react` in the future, similar to [list of ant-design](https://github.com/ant-design/ant-design/). But I can't promise a deadline, now I'm dealing with other components.(let me know please if anyone wants to contribute for this)

**Comment by PaulPCIO** [comment]
When I get some time, I will set up a clean env to test all the components one by one 🤕, sadly I can not seem to access the docs with IE else I would have tested it directly from the docs using a browser stack. have to get back to my project, but I will keep you updated of any progress

**Comment by PaulPCIO** [comment]
okay, there seems to be a polyfill error which I suppose to be the reason why the tickbox and model did not work in my first comments.

![image](https://user-images.githubusercontent.com/39598117/82667653-93344780-9c38-11ea-8435-c4b9c48df470.png)

**Comment by unix** [comment]
@PaulPCIO Thank you for your work.
If you want to test the working effect of `polyfill`, you can fork the project and add `plyfill` to the document site. (e.g. `import something from 'core-js'`)

Let me know if you need help. (Or you can create a new issue to discuss it.)

**Comment by PaulPCIO** [comment]
@unix https://github.com/zeit-ui/react/pull/228 

docs are working 98% in IE 11, next problem I'm not sure how to sort out, I think it's rather something with the babel transpiling of template strings 😅

**Comment by unix** [comment]
Transferred  to #229 .
