### ISSUE TITLE
Add polyfill explanation with compatibility

### ISSUE THREAD

**Issue by PaulPCIO** [zeit-ui/react#229]
# Compatibility `docs`

These following components require a polyfill to be able to use on IE11, it should be added to compatibility docs: https://github.com/zeit-ui/react/issues/226, https://github.com/zeit-ui/react/pull/228

## Polyfill's used:
parseInt: `core-js/fn/number/parse-int`
scroll: `smoothscroll-polyfill`

## Components requiring polyfill's
https://github.com/zeit-ui/react/blob/dc68d6a77cd3b30f84aa7a182c044f82a94569bb/components/utils/color.ts#L9-L11

https://github.com/zeit-ui/react/blob/dc68d6a77cd3b30f84aa7a182c044f82a94569bb/components/shared/dropdown.tsx#L33-L34

https://github.com/zeit-ui/react/blob/dc68d6a77cd3b30f84aa7a182c044f82a94569bb/components/tooltip/tooltip-content.tsx#L48-L51

**Comment by unix** [comment]
I added a [new page](https://github.com/zeit-ui/react/wiki/Environment-Support) in wiki.

All compatibility related information can now be found in the wike page. If anyone has a new point of view, please edit the wiki page.

And, huge thanks to @PaulPCIO 👍

**Comment by PaulPCIO** [comment]
Thanks. @unix , sorry I could not get around to do it myself, head under heals with my current project.
