### ISSUE TITLE
Sidebar styling incorrect

### ISSUE THREAD

**Issue by itshaydendev** [zeit-ui/react#23]
# About `styles` 🛠️

Your version puts the active element in a box with all-caps text.
![image](https://user-images.githubusercontent.com/22327045/77665903-2eca7400-6f78-11ea-835f-836b3d3ca8f3.png)

Zeit's just makes the text bold.
![image](https://user-images.githubusercontent.com/22327045/77665942-3b4ecc80-6f78-11ea-9e56-4abcddd7c1ce.png)

**Comment by unix** [comment]
It's just the style of the document, but I think you're right, I'll fix it.

**Comment by ofekashery** [comment]
@unix I think you should also remove the background, like this: 
![image](https://user-images.githubusercontent.com/16443111/77681434-f89feb00-6f9d-11ea-9442-9bc60783b8c2.png)

**Comment by itshaydendev** [comment]
@ofekashery I did mention that zeit-ui puts it in a box
