### ISSUE TITLE
[select] dropdown auto width

### ISSUE THREAD

**Issue by PaulPCIO** [zeit-ui/react#239]
# About `styles` 🛠️

If you have text that overflows in the select options they are hidden, there should be a prop to enable us to set the containing `.dropdown` because currently the `dropdownClassName` and `dropdownStyle` props gets sent to the `.select-dropdown` and not the parent container, so you cant use them to set the `.dropdown` width to auto

This is without the auto width on **.dropdown**:
![image](https://user-images.githubusercontent.com/39598117/83038163-ee9d7580-a03c-11ea-823c-3397b0e9b965.png)

This is with the auto width on the **.dropdown**:
![image](https://user-images.githubusercontent.com/39598117/83038216-ff4deb80-a03c-11ea-85ec-17c6f8c6514c.png)

**Comment by unix** [comment]
This requires a prop to control whether `Option` follows Select's width, this is common feature, I'll do it.

**Comment by unix** [comment]
@PaulPCIO 
now [v1.6.0](https://github.com/zeit-ui/react/releases/tag/v1.6.0) is out, the new feature is already available.
