### ISSUE TITLE
How do I override styles ?

### ISSUE THREAD

**Issue by belhassen07** [zeit-ui/react#240]
I'm using tailwindcss and my classes are being overridden by the internal stylescreated by @zeit-ui/react?
Is there an easy way to customize styles ?

**Comment by unix** [comment]
All component styles have a weight of 2, you need weights greater than 2 to override them:
```css
.my-app .custom-class {}
```
[Here](https://github.com/zeit-ui/react/blob/master/examples/custom-styles/src/home.jsx) is an example for reference.

**Comment by belhassen07** [comment]
This doesn't seem to be working, here's my code: 

```jsx
export const AddProjectModal = ({ handleClose, open }) => {
  return (
    <div class="modal">
    <Modal open={open} onClose={handleClose} width="35rem" >
      <Modal.Title>Create a project</Modal.Title>
      <Modal.Content>
        // some inputs here
      </Modal.Content>

      <Modal.Action
        class="submit-btn w-full"
        // only inline styles seem to work
        // style={{
        //   fontSize: "1rem",
        //   backgroundColor: "#1d2335",
        //   color: "white",
        // }}
        type="submit"
      >
        Create project
      </Modal.Action>
    </Modal>
    </div>
  );
};
```
**CSS**

````css
.modal .submit {
  background-color: var(--main-color);
}

**Comment by belhassen07** [comment]
Can you elaborate on this ? Thank you 


> All component styles have a weight of 2, you need weights greater than 2 to override them:

**Comment by unix** [comment]
This is [an example](https://codesandbox.io/embed/zeit-ui-override-style-modal-t0r1v?fontsize=14&hidenavigation=1&theme=dark) for override `Modal` style. The conetnt of `Modal` is a [portal component](https://reactjs.org/docs/portals.html), you need to use `wrapClassName` to change the style.

CSS styles have different priority, [here](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity)  are the detailed documents. 

Please reply me if you have any updates.

**Comment by belhassen07** [comment]
The wrapClassName solved it. Thank you !
