### ISSUE TITLE
form can't submit when outside the Modal

### ISSUE THREAD

**Issue by belhassen07** [zeit-ui/react#245]
# Bug report 🐞
form works when the form is inside the Modal component but the Modal.Action loses its default styling. 
When wrapping the Modal inside the form, the submit button doesn't work
## Version & Environment
"@zeit-ui/react": "^1.6.0-canary.2",
 "preact": "^10.1.0",

OS: Windows 10 64bits
Google Chrome Version 81.0.4044.138 (Official Build) (64-bit)

## Expection
Expecting the form to be submitted when form wraps modal

## Actual results (or Errors)
it doesn't submit

**Comment by unix** [comment]
[Here](https://codesandbox.io/embed/eloquent-cerf-buhl7?fontsize=14&hidenavigation=1&theme=dark) is an online example, `Molda` with `Form` seem to work correctly, can you provide more information to help me reproduce the issue? (Or  a online sample?)

**Comment by belhassen07** [comment]
The form attribute worked like a charm. I really appreciate your support buddy, best I've ever got. Thank you for your patience ! 🙏
