### ISSUE TITLE
[request] Sizing of components and config of font sizes

### ISSUE THREAD

**Issue by PaulPCIO** [zeit-ui/react#247]
# About `styles` 🛠️
So this may be merits to be broken down into multiple issues, but to address sizing;

The components like `select, button, inputs` etc should all follow the same sizing, currently take a button next to select, you will notice that the button height is always more than the select.
![image](https://user-images.githubusercontent.com/39598117/83128345-97021700-a0db-11ea-9c5d-4ec28418f6d3.png)

Then more of a feature request. Will, it possible to add a config to the ThemeProvider to enable the changing of base fonts for different sizes,  `'mini', 'small', 'medium', 'large'`?

**Comment by unix** [comment]
1. Different component have different sizes, it's design style, you can notice that other component lib do the same. We don't want to pursue the same height.

2. There is no plan to extend the sizes prop temporarily, different components have different cardinality scaling values. Maybe in the future, `size` prop may support `number`, but now it doesn't seem necessary, I can't promise this feature.

All in all, the goal of component lib does not include the pursuit of consistent height. If you want more customization, you can use the `className` to override style. If you just want to scale components, `transform` can easily solve this task: 

```css
.custom-style { transform: scale(0.75); }
```
