### ISSUE TITLE
Button loading does not display right when set "auto" width

### ISSUE THREAD

**Issue by sondh0127** [zeit-ui/react#251]
# About `styles` 🛠️
- Produce code
`
		<Button
          auto
          size="small"
          htmlType="submit"
          type="success"
          disabled={!formState.isValid}
          loading={true}
        >
          Submit
        </Button>
`
- Scrrenshot
![2020-05-29_11-16](https://user-images.githubusercontent.com/62163604/83220735-0b04f380-a19e-11ea-9556-c525706f037d.png)

**Comment by unix** [comment]
Version `1.6.2` will be released later.
