### ISSUE TITLE
Skeleton component

### ISSUE THREAD

**Issue by PaulPCIO** [zeit-ui/react#256]
# Feature request 🚀

It would be nice to have [skeleton](https://ant.design/components/skeleton/) component(s) similar to ant.design

also, check out the [card loading](https://ant.design/components/card/#components-card-demo-loading) example(s)

### Examples:
https://ant.design/components/skeleton/
![image](https://user-images.githubusercontent.com/39598117/83725986-2743dd00-a643-11ea-855a-1db51a88bf45.png)

https://ant.design/components/card/#components-card-demo-loading
![image](https://user-images.githubusercontent.com/39598117/83725732-b69cc080-a642-11ea-8c31-9c1149bef7d2.png)

**Comment by unix** [comment]
Skeleton is good solution, but this component is highly intrsive to user's projects, and it's very difficult to maintain. For everyone, add Skeleton component to project manually is a compromise for optimization. (for engineering)

Technically, there are some unsolvable problems with such components (Skeleton loading):
  - Unable to display multiple lines of text accurately.
  - Unable to confirm height of element, often leads to re-flow.
  - SSR has completed part of its historical mission.

However, I also often use Skeleton on business projects, maintaning bloated business components 😢 . In fact, I thought about this component when I created this project, but I haven't found a good balance. 

Well, I will implement this type of component, but I can't give you a deadline, unless I have a new idea about skeleton loading. I'm still thinking and researching something about it, and I'm also eager to hear anyone's new ideas or articles.

**Comment by unix** [comment]
I'll close this discussion because I don't have a good solution right now.
Anyone with an idea about `Skeleton`, please reply to me.

**Comment by arguiot** [comment]
@unix I'd like to reopen this issue as Vercel has a [`Skeleton`](https://vercel.com/design/skeleton) component on their version of Geist. I'm not sure to fully understand the relation between Geist-Org and Vercel but I'd like to see a bit more consistency between the two versions.
