### ISSUE TITLE
Extending input component (typescript)

### ISSUE THREAD

**Issue by antoniojps** [zeit-ui/react#259]
# Help wanted

This is more of a **typescript** question, how can I extend a component's types?
The default props types seem to override the component types (not sure).

I'm trying to add a `error` prop for showing a small error text, here's my Input component:

```tsx
import { Input, Spacer, Text } from '@zeit-ui/react'
import { InputProps } from '@zeit-ui/react/dist/input/input'

type InputErrorType = {
  error?: string | null
}

const InputCustom = ({
  error = null,
  status = 'default',
  ...inputProps
}: InputErrorType & InputProps): ReactElement => {
  const hasError = typeof error === 'string' && error.trim() !== ''
  return (
    <>
      <Input status={hasError ? 'error' : status} {...inputProps} />
      {hasError && (
        <>
          <Spacer y={0.4} />
          <Text small type="error" size="var(--size-xs2)">
            {error}
          </Text>
        </>
      )}
    </>
  )
}
```

When using the component like so:
```tsx
<Input error="this is required" />
```

I get the type check error:
`Property 'autoComplete' is missing in type '{ error: string; }' but required in type 'Props'.`

This is most likely an issue with how I am setting up the types, but I wish there was some documentation examples on how to use the library types.

**Reproduction**: https://codesandbox.io/s/laughing-germain-ibwc1?file=/src/Input.tsx

**Comment by unix** [comment]
Considering type of the default values and sub-component, the props types of all components of `zeit-ui/react` are rewritten. If you need to get the props type of runtime component, you can use `React.ComponentProps`. 

[Here is an example for reference.](https://codesandbox.io/s/zeit-ui-react-extends-componet-2jdqj?file=/src/Input.tsx)

**Comment by antoniojps** [comment]
@unix Thank you!

**Comment by unix** [comment]
For everyone with similar priblems, `zeit-ui/react` now inlcudes [a sample project](https://github.com/zeit-ui/react/blob/master/examples/extends-components/README.md) for reference.
