### ISSUE TITLE
Add helperText prop for Input component

### ISSUE THREAD

**Issue by h2o7** [zeit-ui/react#263]
# Feature request 🚀
Equivalent of helperText prop in Material UI

### Expected:
  - No breaking changes
  - Color of helper text would depend on input status

### Examples:
```js
<Input placeholder="The Evil Rabbit"  helperText="xyz" />
```

### Programme:
None
### Others:
None

**Comment by h2o7** [comment]
@unix if you think this should be added, I can create a PR in couple days.

**Comment by unix** [comment]
The `helper text` is not a standard attribute for `Input`, it's just an enhancement of material ui form system, in the component library of antd, forms have a similar implementaion.

It should be noted that we do not have any plans to add `form` at present, you can use `zeit-ui/react` with other form libraries. if you just want a help text only, it's a good choice to inherit the component and your own functions. [please refer to this example](https://codesandbox.io/s/zeit-ui-react-extends-component-2jdqj)

**Comment by h2o7** [comment]
@unix sounds good and is easy enough. Closing this issue.
