### ISSUE TITLE
Don't close Modal onMouseUp

### ISSUE THREAD

**Issue by snelsi** [zeit-ui/react#264]
# About 'Modal' behavior 🛠️
Currently, the Modal will close not only on outside full click, but even if 'mouseDown' was pressed inside Modal and 'mouseUp' happened outside. This leading to some unexpected, unintentional closes of the dialog, which leads to bad user experience and potential input loss.

Look at the attached video to get a showcase of this behavior:
https://streamable.com/4zgl2f

In the attached example I'm trying to select text in my Input, but end up closing whole Dialog instead. 😥

**Comment by snelsi** [comment]
You can check out this behavior on [documentation page](https://react.zeit-ui.co/en-us/components/modal) examples.
Selecting text is tricky, cause you need to stop strictly inside Modal component. Otherwise, it'll just close itself.

**Comment by unix** [comment]
This is an unexpected bug, I'll fix it ASAP.

**Comment by unix** [comment]
@snelsi You can update version to fix it:
Released: `stable: v1.6.3`, `pre-release: v1.7.0-canary.3`
