### ISSUE TITLE
Add a working next.js tree shaking demo

### ISSUE THREAD

**Issue by h2o7** [zeit-ui/react#266]
# About `docs`

```
{
  "presets": ["next/babel"],
  "plugins": [
    [
      "import",
      {
        "libraryName": "@zeit-ui/react",
        "libraryDirectory": "esm"
      }
    ]
  ]
}
```
doesn't work as you can see below: 
![image](https://user-images.githubusercontent.com/22069968/84209649-483d7f80-aad4-11ea-92d4-edd7baa6754b.png)

**Comment by unix** [comment]
I'll add an example for `next.js` later.

**Comment by unix** [comment]
You can refer to [this example](https://github.com/zeit-ui/react/blob/master/examples/tree-shaking-nextjs/README.md), if you still have any questions, please reopen it.
