### ISSUE TITLE
Radio value should also accept numbers

### ISSUE THREAD

**Issue by 7ma7X** [zeit-ui/react#269]
# Feature request 🚀

Currently `value` in `Radio.Props` and `Radio.Group.Props` is set to `string`.

http://react.zeit-ui.co/en-us/components/radio

Though you can convert number to string easily by template literals, it would be nicer to use `number` props directly.

### Expected:
  - No breaking changes

### Examples:
```js
<Radio value={1}>Option 1</Radio>
```

**Comment by unix** [comment]
I agree with you, a value of type `number` is very helpful for `Radio`.

**Comment by unix** [comment]
A pre-release version is about to be outed. (`v1.7.0-canary.4`)

**Comment by 7ma7X** [comment]
Thank you very much 👍
