### ISSUE TITLE
Collapse has performance Issue/Is lagging/stuttering

### ISSUE THREAD

**Issue by surajmandalcell** [zeit-ui/react#270]
# Bug report 🐞
Performance Issue/Is lagging/stuttering

## Version & Environment
^1.7.0-canary.3 
Windows 10 Pro Version 2004

## Expection
The collapse component should collapse in and out smoothly.

## Actual results (or Errors)
It's stuttering and lagging for some reason.

**Comment by unix** [comment]
Please provide browser name and version for me to reproduce the problem.

**Comment by surajmandalcell** [comment]
Google Chrome 
Version 83.0.4103.97 (Official Build) (64-bit)

**Comment by unix** [comment]
I have installed your specified version of windows system and chrorm browser, but it looks like work normal: https://streamable.com/py0zyt

**Comment by unix** [comment]
I'll close it because the problem can't be reproduced.
If someone can provide more details or video, just reopen it.
