### ISSUE TITLE
MockPage 的使用

### ISSUE THREAD

**Issue by Jafee** [zeit-ui/react#272]
文档中：https://react.zeit-ui.co/zh-cn/components/page 使用了MockPage

但是我没找到怎么引用MockPage，我把 Component 下的 mock-page 拷贝到项目中，引入时依然是解析错误。

辛苦作者指导一下正确的引入方法。

**Comment by unix** [comment]
`Page` 是一个组件，用于展示一个页面，常见的使用场景是放在 App 的入口处。
`MockPage` 只是示例中为了展示 `Page` 组件的示例容器，在一个新的弹出层上查看 `Page` 的效果。实际上没有 `MockPage` 这个组件。

**Comment by Jafee** [comment]
明白了，谢谢 @unix 。
