### ISSUE TITLE
Lighthouse Best Practices improvement

### ISSUE THREAD

**Issue by juanhelbert** [zeit-ui/react#273]
# Feature request 🚀

It would be nice to have a `rel` prop on [Image.Browser.Props](https://react.zeit-ui.co/en-us/components/image#image.browser.props) where you can define a `rel="noopener"` or `rel="noreferrer"` to avoid Lighthouse's best practice errors.

### Example:
It would be great to do something like this:
![image](https://user-images.githubusercontent.com/28510953/84540646-3e7e6c80-accc-11ea-9093-2c8272099e9c.png)

but avoiding the Lighthouse's error `Add rel="noopener" or rel="noreferrer" to any external...`

![image](https://user-images.githubusercontent.com/28510953/84541115-19d6c480-accd-11ea-86ae-d79534882181.png)

Maybe with something like this:
  ```js
  type = 'noopener' | 'noreferrer' 

  <Image.Browser url="..." rel={type} >
    <Image ... />
  </Image.Browser>
  ```

or doing it by default, because the `Image.Browser` has a
```html
<a target="_blank" />
```

**Comment by unix** [comment]
The latest version(pre-release) has been outed: (`v1.7.0-canary.5`)
  - `Image.Browser` now supports all attributes from `AnchorElement`.
