### ISSUE TITLE
Display flex for Grid component

### ISSUE THREAD

**Issue by fabricionaweb** [zeit-ui/react#284]
With the changes on #280 the default display for Grid component (in my case it was `block`) now changed to `flex` but I need at least flex-wrap (or the previous default display block was fine)

I have some ideas:

- Create a prop to `wrap` into Grid component (like Grid.container has)
- Dont change the display prop in Grid component, maybe just remove it ([instead of set to flex](https://github.com/unix/react/blob/ebd8d6cdd815eb4b3ccea85722646e0314b51866/components/grid/basic-item.tsx#L38))
- Ability to pass `styles` through Grid component

What do you think guys?

**Comment by unix** [comment]
Agreed with you.

  1. The extra style `display: flex` is an error, I'll remove it, back to previous version.
  2. It's an error that `style` can't be used on `Grid`, and I'll fix it.

**Comment by unix** [comment]
@fabricionaweb 
 `v1.7.2` released, it should solved this issue.

**Comment by fabricionaweb** [comment]
So quickly, thanks for you job man, awesome :D
