### ISSUE TITLE
button automatically capitalizes text - should be an arg or have a way to disable this

### ISSUE THREAD

**Issue by bryanhpchiang** [zeit-ui/react#294]
macos node
<img width="822" alt="Screen Shot 2020-06-28 at 6 26 36 AM" src="https://user-images.githubusercontent.com/10623745/85948912-6397ef80-b908-11ea-972b-1697fb2f813c.png">

**Comment by unix** [comment]
It's a good design style, if you want to cancel it: https://codesandbox.io/s/zeit-ui-react-button-without-transform-w4b9r
