### ISSUE TITLE
modal is not vertically centered - not sure if this is intended behavior, looks offset to me

### ISSUE THREAD

**Issue by bryanhpchiang** [zeit-ui/react#295]
macos node
just a standard use of modal from the example, i can provide more code if necessary
<img width="1680" alt="Screen Shot 2020-06-27 at 3 32 32 PM" src="https://user-images.githubusercontent.com/10623745/85948932-8c1fe980-b908-11ea-927c-021249a52cd4.png">

**Comment by unix** [comment]
This is a feature, the position of `Modal` will be shifted upward.
