### ISSUE TITLE
modal is sluggish on close compared to official implementation

### ISSUE THREAD

**Issue by bryanhpchiang** [zeit-ui/react#296]
zeit-ui: https://react.zeit-ui.co/en-us/components/modal
official vercel: https://vercel.com/design/modal

for zeit-ui, the modal slides up and fades away, however after it slides up it takes an extra ~0.2-0.3 seconds before it is fully gone.
in the vercel version, by the time it slides up it's fully gone.

this compromises end user experience.

**Comment by unix** [comment]
I have made some optimization in canary version, do you have any specific suggestions for improvement?
https://react-rc.zeit-ui.co/en-us/components/modal

**Comment by bryanhpchiang** [comment]
this is a lot better!!! thanks for the improvement :)
