### ISSUE TITLE
Change Table API

### ISSUE THREAD

**Issue by AugustoConti** [zeit-ui/react#301]
Hi :wave: @unix !

What do you think if we change the Table API for:

```js
<Table>
  <Table.Head>
    <Table.Cell align="left">PROPERTY</Table.Cell>
    <Table.Cell align="left">DESCRIPTION</Table.Cell>
    <Table.Cell align="left">TYPE</Table.Cell>
    <Table.Cell align="left">DEFAULT</Table.Cell>
  </Table.Head>
  <Table.Row>
    <Table.Cell>type</Table.Cell>
    <Table.Cell>Content type</Table.Cell>
    <Table.Cell>secondary | warning | error | success</Table.Cell>
    <Table.Cell>-</Table.Cell>
  </Table.Row>
  <Table.Row>
    <Table.Cell>Component</Table.Cell>
    <Table.Cell>DOM element to use</Table.Cell>
    <Table.Cell>string</Table.Cell>
    <Table.Cell>-</Table.Cell>
  </Table.Row>
  <Table.Row>
    <Table.Cell>bold</Table.Cell>
    <Table.Cell>Bold style</Table.Cell>
    <Table.Cell>boolean</Table.Cell>
    <Table.Cell>false</Table.Cell>
  </Table.Row>
</Table>
```

I think so it gives the user much more control over what and how to render.

Copy the example from [Vercel](https://vercel.com/design/table).

If you agree, I can take care of it.

**Comment by unix** [comment]
Please edit the issue according to the template.

----

It seems that you just need the table style, if so, you can refer to the code [here](https://github.com/zeit-ui/react/blob/master/lib/components/attributes/attributes.tsx).

If not (you really want to change APIs): I have no plans to change the table API for the time being, these two styles have their own advantages and disadvantages, you can see that both [antd](https://ant.design/components/table/#components-table-demo-basic) and [material](https://material-ui.com/components/tables/) have their own implementations.

If you have any other features about `Table`, please open a new issue.
