### ISSUE TITLE
disablebackdropclick on modal broken

### ISSUE THREAD

**Issue by bryanhpchiang** [zeit-ui/react#310]
# Bug report 🐞

## Version & Environment

macos 10.15 
chrome Version 83.0.4103.116 (Official Build) (64-bit)
zeit-ui/react 1.7.6
  - Version of browser
  - Version of `zeit-ui/react`

## Expection

The behavior I expect is ...

disablebackdropclick works

## Actual results (or Errors)
doesn't work

I got an error:

if you go here
https://react.zeit-ui.co/en-us/components/modal#customizable
and add disableBackdropClick to the props or disableBackdropClick={true}, it doesn't work
for the other examples it works, but in my own project it doesn't work, so not sure what's going on

**Comment by ofekashery** [comment]
The ``disableBackdropClick` requires an ``Modal.Action``, which doesn't exist in the customizable example.

**Comment by bryanhpchiang** [comment]
got it thanks, might be good to note that in the docs
