### ISSUE TITLE
inline label for select

### ISSUE THREAD

**Issue by bryanhpchiang** [zeit-ui/react#311]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

  - Component or something else

<Input> component has a inline label prop, might be nice to have one for <Select> bc it can help forms look nicer

### Examples

```jsx
<Select label="helllo">
...
</Select>
```

**Comment by unix** [comment]
This feature will not be added, related issue: #263 .
