### ISSUE TITLE
change width of toast

### ISSUE THREAD

**Issue by bryanhpchiang** [zeit-ui/react#312]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

  - Component or something else

<Button> has auto option, Toast should adjust to height of content, looks weird when it doesn't

### Examples

```jsx
```

**Comment by unix** [comment]
This is a suggestion that can be improved, I will try to optimize the display of multiline text in `Toast`.

**Comment by unix** [comment]
@bryanhpchiang This issue has been moved #315 .
