### ISSUE TITLE
modal content default max-height

### ISSUE THREAD

**Issue by bryanhpchiang** [zeit-ui/react#314]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

  - Component or something else

right now modal has a max-height of some arbitrary number (for the content), not sure why this exists - easy to set max-height by yourself, difficult to remove it

can test for yourself in https://react.zeit-ui.co/en-us/components/modal

### Examples

```jsx
```

**Comment by unix** [comment]
Set `wrapClassName` prop can be custom.
