### ISSUE TITLE
Feature request for IconOnly Button component

### ISSUE THREAD

**Issue by firede** [zeit-ui/react#316]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

  - IconOnly Button

### Examples

```jsx
<Button icon={<Settings />} type="success" auto size="small" />
```
#### current
<img src="https://user-images.githubusercontent.com/157338/86515666-2faf5380-be4d-11ea-9264-323f54e45e00.png" width="82" />

#### expected
<img src="https://user-images.githubusercontent.com/157338/86515718-a0ef0680-be4d-11ea-9182-6c2bac9a8d2e.png" width="79" />

**Comment by unix** [comment]
Good thinking! I'll deal with it.

**Comment by unix** [comment]
@firede This feature is added here: #319 .
Note that the `height` and `width` of the `Button` are not equal, if you just want a square `Button`, you can modify it like this:

```jsx
<Button icon={<Settings />} auto style={{ width: 'var(--zeit-ui-button-height)', padding: 0 }} />

// or customize your own button:
const MyButton = ({ children, ...props }) => (
   <Button style={{ width: 'var(--zeit-ui-button-height)', padding: 0 }} {...props}>{children}</Button>
)
```

**Comment by unix** [comment]
The pre-release version `1.8.0-canary.4` is now available.

**Comment by firede** [comment]
It looks great👍, thanks!
