### ISSUE TITLE
reopening issue for dynamic styling - not resolved

### ISSUE THREAD

**Issue by bryanhpchiang** [zeit-ui/react#317]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

  - Component or something else

reopening https://github.com/zeit-ui/react/issues/313
so I can do custom styling like so
```
<Avatar className="my-avatar" ... />
.my-avatar {
background: "black";
}
```
but if I want to do this dynamically for instance to set background to a color based on props how would i do that

please don't just close issues with no explanation - not productive thanks

### Examples

```jsx
```

**Comment by unix** [comment]
[Here an online example](https://codesandbox.io/s/zeit-ui-change-avatar-bg-q2t7h?file=/src/app.js), I'll give you 4 of the simplest solutions.

I mentioned the issue of weight in #240 :

> All component styles have a weight of 2, you need weights greater than 2 to override them.
> CSS styles have different priority, here are the detailed documents.

You just need to use any style that is higher than your current weight, If you think `weight` is boring you, Any JSS solution can easily solve this problem. such as [styled-jsx](https://github.com/vercel/styled-jsx), it's easier to add overlay styles:

```jsx
import { resolve } from 'styled-jsx/css'
const { className, styles } = resolve`
    background: ...
`

const MyAvatar = ({ ...props }) => <Avatar className={className} {...props}>{styles}</Avatar>
```

**Comment by bryanhpchiang** [comment]
got it thanks this is really helpful
