### ISSUE TITLE
Add Playroom

### ISSUE THREAD

**Issue by dferber90** [zeit-ui/react#321]
# Feature request 🚀

  - [x] I will create Pull Request
  - [ ] It's just a suggestion

### Expected

<p align="center">
<a href="https://zeit-playroom.vercel.app/#?code=N4Igxg9gJgpiBcIA8BlADgQzDATgAgE8BeYARgF88B6APgB0A7JAYQgYBcMBLB3ehvHlSZs%2BAB4kKtRoJYYcUPAGcAFhigQA7v0GyVAFhoAtAKIBJACp4AqmbwAlGFnZIqBnbqRoaAWWi4BDAZFAFseLhCMABsuJXYHJzB42zwYgCMceQIAOldvGU9meShsgDEICHY%2BAt0hABkeAGs8SCiIfE4cAHMYdiI6EAB9NKigxoG8FRwYADN%2BkBV2djQleCoqLq52FQBXNOzIEKoALxgtgFodripp5wGaADVYreUIHZxsFv88NjwAcS2AAk9rkqA0GI0PLIqEUFGUKlUcB5XLCoMj0FhcHgJGRKNImDC2JweHwQOQgA" target="_blank">
<img width="720" alt="Playroom preview" src="https://user-images.githubusercontent.com/1765075/86726534-50d19900-c033-11ea-87a9-18085d01be82.png">
</a>
</p>

A [Playroom](https://github.com/seek-oss/playroom) lets developers quickly prototype new designs across different screen sizes and themes without having to install the package locally. Playroom was created by SEEK and is super useful to show how components of a Design System come together to form views.

Here is an example of a more complete Playroom: [Responsive form example](https://seek-oss.github.io/braid-design-system/playroom/#?code=N4Igxg9gJgpiBcIA8BhAhgJygPgDoDsACQpAZQBc0wBrQgZwAcqYBeXEAG0wHMZ28ixEgAkYaKAEt83QhxgA3GBzYgAzPwCCUKIQwQ5SAPSjxU7gKEkKVagALGzFsADa7OgFs0HDuwA0hdi4MXnYAXQBfC0sSDQBXcgg6WO5eOnICaKEuACMlFQApCGzCcglyOXYMzPpk1NKIfDonV0FqwmAqtuJyGAAPcngAkAARBSUIBhgMP07q8N9ZzI7Wrp7+wfZRuglufCmZlcz5xejlrqE1gaGABT0oWLByQgBZNHw0XmmQBcPo49-iBEToYopYkAAVPrkABiEiUOhyeXYKAg7iY+AAnoR3u4+CBCCCTkhng1yAALa4SGhTWRoXLKdjWDA9KDsAmgoQQqGYMQnYiwOhgDASBj1fAqUixdyeYV0GCEDEQWIYXQwRgNbbZCQcMpwuj+OjUbUcOiEN46KhkuGKXH4ch0AB0lQBtPpKi2QpFYudbTlkHwUEwGIAMnSkSAMDBINKYAGYKyQMCOcQkBpHhINcnOQAheIJfDYUhoRRGXPkfNZoxpsV0DlGaw0KL1yiNghGdBYATfEDkmC4ugIZwgCBgMAgUK+EAAdwkUHJA-gzlUACYAAy+ACMq+XABYIkA)

I would like to propose adding a Playroom for zeit-ui.

This might tie in nicely with #262 where you could use the Playroom to show off the best practices.

The Playroom will only work for the React components.

### Examples

I went ahead and created a Playroom (in TypeScript) for zeit-ui at [@dferber90/playroom](https://github.com/dferber90/zeit-playroom). It is deployed to [zeit-playroom.vercel.app](https://zeit-playroom.vercel.app/).

### Further steps

If you are interested in having an official Playroom, we could:
- [x] move the repo to the zeit-ui org
- [x] host the Playroom on the zeit-ui domain (e.g. at playroom.react.zeit-ui.co)
- [ ] link to the Playroom from the main navigation, [like this](https://user-images.githubusercontent.com/1765075/86722851-000c7100-c030-11ea-95f2-a9ec9bd2886c.png)
- [ ] adjust the "widths" (available Playroom screen sizes) to fit the zeit-ui breakpoints

The Playroom is set up and working. However, we could improve the following things later on:
- [ ] Make auto completion work in Playroom
- [ ] Add more [snippets]([`snippets`](https://github.com/dferber90/zeit-playroom/blob/7d8d85b12b3253d3363235c2f346f3ae325976be/snippets/index.ts))
- [ ] add a link to this Playroom to the [Playroom Demos](https://github.com/seek-oss/playroom/blob/master/README.md#demos) secion of the README to make more people aware of zeit-ui/react

### Maintenance

I see the following maintenance cost for having a Playroom:
- keeping available [`components`](https://github.com/dferber90/zeit-playroom/blob/7d8d85b12b3253d3363235c2f346f3ae325976be/components/index.ts) in sync with `@zeit-ui/react`
- updating [`snippets`](https://github.com/dferber90/zeit-playroom/blob/7d8d85b12b3253d3363235c2f346f3ae325976be/snippets/index.ts) when new components are created or changed
- upgrading dependencies

### Alternatives

There are two ways to integrate the Playroom. I chose a separate domain and repository. It would also be possible to mix the playroom into the `zeit-ui/react` repo and host it at `react.zeit-ui.co/playroom`.

**Comment by unix** [comment]
❤️ Brilliant!
Agreed with you. If you accept, you can donate the project to `zeit-ui`, then use Pull Request to maintain the repo, how do you feel?

**Comment by unix** [comment]
About the specific implementation process, I have the following suggestions:
  - Maintain a separate repository, and separate domain name (`playroom.react.zeit-ui.co`)
  - Add link in `react.zeit-ui.co`
  - Use links to jump to an external site(`playroom.react.zeit-ui.co`) instead of editing in the current document site. In this way, the editing area can be large and without considering preloading. For example, add an item (`playroom`) to the menu on the left, then write some guide document and add an external link.

**Comment by dferber90** [comment]
Sure!

You'd need to make me part of the zeit-ui GitHub org and give me permission to create new repos in order for me to be able to move the project over, as shown [here](https://user-images.githubusercontent.com/1765075/86746056-749cdb00-c043-11ea-80f3-764f85727f47.png).

If you feel comfortable accepting me into the zeit-ui org and extending commit-rights to the playroom repo, it would make it easier for me to help with maintenance.

Currently Vercel is set up as a private project and used to deploy the Playroom to zeit-playroom.vercel.app. Once the repo is moved over, you could add it to your own Vercel account and set up the subdomain at playroom.react.zeit-ui.co. Would you like to do that?

**Comment by unix** [comment]
@dferber90 
I sent you an invitation, now you have the admin of repo [react-playroom](https://github.com/zeit-ui/react-playroom), the repo will be automatically deployed to `playroom.react.zeit-ui.co`. (If you need to modify repo `zeit-ui/react`, please create a PR.)

If you want to discuss anything with me in private, you can join our slack through [this link](https://join.slack.com/t/zeit-ui/shared_invite/zt-f17270gz-yIT9gaCIAsUEBYjjzz4ryg).

**Comment by dferber90** [comment]
I now did the following steps:
- force-pushed the repo to zeit-ui/react-playroom
- deleted dferber90/zeit-playroom
- deleted the Vercel deployment

> Use links to jump to an external site (playroom.react.zeit-ui.co) instead of editing in the current document site. In this way, the editing area can be large and without considering preloading. For example, add an item (playroom) to the menu on the left, then write some guide document and add an external link.

I really like that the current Zeit UI Playground is editable. The Playroom would be a nice addition but shouldn't replace the existing Playground. I think this is what you're saying too.

It seems possible to add the Playroom button/link to the Playground. Playroom reads its initial settings/code from a `?code=xy` param.  We should be able to generate the initial code from the passed `code` prop. [Here](https://github.com/seek-oss/playroom/blob/3b1cabd45544bb8d424aafedb674df361e89dc70/utils/index.js#L1-L11) is how it's done in Playroom. So we should be able to create our own [`createUrl`](https://github.com/seek-oss/playroom/blob/3b1cabd45544bb8d424aafedb674df361e89dc70/utils/index.js#L13-L29) function. We can then create our own links which open Playroom with the code of the Playground.

**Comment by dferber90** [comment]
For the Vercel build settings, you'll need to set `yarn build` as the build command, and `dist` as the "public" folder.

**Comment by unix** [comment]
> It seems possible to add the Playroom button/link to the Playground. Playroom reads its initial settings/code from a ?code=xy param. We should be able to generate the initial code from the passed code prop. Here is how it's done in Playroom. So we should be able to create our own createUrl function. We can then create our own links which open Playroom with the code of the Playground.

This seems to be similar to the `codesandbox` link of other component libs, the reason why I didn't do this (add external online editor) that the current Playground is already editable, it doesn't seem necessary to add an extra editor for each example.

I know that many component libs add a lot of links (e.g. Playroom / Codepen / Stackblitz etc) to each example, but this is not a big improvement for the experience of our component example? I'd like to hear from you @dferber90 .

**Comment by dferber90** [comment]
It's totally up to you and I appreciate that you put so much effort into keeping it simple.

The benefits I see of having Playroom are:
- Playground is limited to the components passed into the playground, whereas Playroom would allow you to extend the current example with any component
- Playground shows different sizes and themes at once

I personally clicked the "Open in Playground" button on the Braid design docs many times. An example of such a button can be seen [here](https://seek-oss.github.io/braid-design-system/examples/basic-form).

**Comment by unix** [comment]
Now some examples include JavaScript code because of the `hooks`, and other examples refer to components in document folders(`/libs/components`).
If we add `Playroom` to each example, just to make it possible to use other components or different sizes, the cost of maintenance is far from the effectiveness. (In the long run, the cost of maintenance is greatly increased, but the improved experience is not obvious.)

**Comment by dferber90** [comment]
Right, the included JavaScript is a good point. You could have a `playroom` prop as `<Playground playroom />` which would turn on the link to Playroom.

I don't get the maintenance point. The link to Playroom can be auto-generated from the `code` prop which is passed to `<Playground />` anyhow. So `<Playground code={`<Button>Submit</Button>`} />` could take the string passed to `code`, automatically transform it using the [`createUrl`](https://github.com/seek-oss/playroom/blob/3b1cabd45544bb8d424aafedb674df361e89dc70/utils/index.js#L13-L29) function and then you'd be able to create an "Open in Playroom" link. Maybe we're talking about different things?

Anyhow, all this is something nice-to-have we could do in the future. For now it would be cool to just get Playroom up and running. The tasks with the highest payoff would probably be to:
- add more snippets (to [`snippets/index.ts`](https://github.com/zeit-ui/react-playroom/blob/master/snippets/index.ts))
- add the link to playroom to the docs, maybe [as a separate nav item](https://user-images.githubusercontent.com/1765075/86722851-000c7100-c030-11ea-95f2-a9ec9bd2886c.png)?

**Comment by unix** [comment]
I mean, some examples don't automatically generate, e.g. `useInput` / `Page` / `useBodyScroll` etc. Or do we  have any way to edit the component itself in `Playroom`? (includes `hooks` / `handler function` / `console.log`, in a few examples, the JS code is part of the component.)

----

> Anyhow, all this is something nice-to-have we could do in the future ......

I really agree with what you're doing.

**Comment by unix** [comment]
Update:
  After using `Playroom` deeply, I don't think `Playroom` is a perfect product, at this stage, its experience needs to be improved.
  So, @dferber90 , thank you for your work, the [zeit-ui/react-playroom](https://github.com/zeit-ui/react-playroom) can be retained as a guide, but I won't link `Playroom` page on the document site.

**Comment by dferber90** [comment]
I'm a bit surprised by the decision, but it's your call and I accept it.

Have a nice Sunday and thanks for looking into it!
