### ISSUE TITLE
better desc for text

### ISSUE THREAD

**Issue by bryanhpchiang** [zeit-ui/react#323]
# About `docs`

This is a document site related issue.

### Languages

  - [x] English
  - [ ] Chinese

### Description
just a nit since most are self-explanatory
but descriptions could b more specific

<img width="261" alt="Screen Shot 2020-07-09 at 3 48 31 PM" src="https://user-images.githubusercontent.com/10623745/87098224-a658a200-c1fb-11ea-980d-6b15233ba9d9.png">

### Page Links (Optional)
https://react.zeit-ui.co/en-us/components/text

**Comment by unix** [comment]
Each component has an "Edit" button at the bottom of the document page, if you have a better idea, try editing them directly.
