### ISSUE TITLE
modal onclosed

### ISSUE THREAD

**Issue by bryanhpchiang** [zeit-ui/react#327]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

  - Component or something else

<Modal onClosed={}>

right now ther's onClose but it runs before the animation is complete, causes issue when same state variable is used both as open prop and in the content

### Examples

```jsx
```

**Comment by unix** [comment]
This issue will be closed because the issue did not follow the template and lacks sufficient description information.
