### ISSUE TITLE
modal.action loading

### ISSUE THREAD

**Issue by bryanhpchiang** [zeit-ui/react#328]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

  - Component or something else

<Button has loading attribute, might be useful for Modal.Action? not sure if this is out of scope
### Examples

```jsx
<Modal.action loading={loading}/>

```

**Comment by unix** [comment]
No, currently, `Action` does not inherit all `Button` component props.
