### ISSUE TITLE
Reopening #328 - <Modal.Action> loading prop

### ISSUE THREAD

**Issue by bryanhpchiang** [zeit-ui/react#330]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

  - Component or something else

Reopening https://github.com/zeit-ui/react/issues/328 since it was closed prematurely without further discussion. Obviously Modal.Action doesn't inherit all of the Button props, but it is an extremely common pattern for a modal to display a <Loading> component after clicking (refer to any Facebook or Google service for example). 

Not requesting this to be made, but am bringing it up since it's a fairly common use case.

### Examples

```jsx
<Modal.Action loading={true}> ...

```

**Comment by unix** [comment]
Currently, the implementation of `Modal.Action` is separate, it does not inherit from `Button`, so it doesn't  have `loading`. 
Adding this set of logic to `Action` alone seems cumbersome, but I will consider refactoring `Action`.

And for issues that are closed, [see the answers here](https://github.com/zeit-ui/react/issues/331#issuecomment-658031638).
