### ISSUE TITLE
Reopening #327 - Modal onClosed prop

### ISSUE THREAD

**Issue by bryanhpchiang** [zeit-ui/react#331]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

  - Component or something else

Reopening #327 since it was closed prematurely. Currently, Modal provides onClose event, but it could also be helpful to provide an onClosed event after the animation completes, since the content of the Modal may be used in the `open` prop as well, so it needs to be displayed until the animation completes.

Side note: I've requested this in the past, but it would be greatly appreciated if issues were not closed immediately after opening. You can simply request clarification and keep it open a day - closing issues wastes my time since I need to open another one, it wastes your time since you need to process another issue, and it wastes other people's time since they need to sift through many closed issues with minimal explanations. I open issues not because it benefits me specifically but because I enjoy using the library and hope that it can be improved for everyone's common use cases -- I appreciate your (the maintainer's) efforts + all the other contributors, but as an active user I hope suggestions can be received in good faith.

### Examples

```jsx
<Modal onClosed={} />
```

**Comment by unix** [comment]
If you need to propose a feature, please give a detailed example and why you need it. To ensure that others understand your intentions, a picture, video, or online example is a good choice. The reality is that you haven't even changed the `Expected` option, it's a default character.

I'm very honored to have received so many suggestions form you, but like a document or repo, the quality of an issue depends on whether you edit or think carefully. I don't mean to blame anyone, I just hope that you will respect the template and explain as much information as possible when leaving issues, especially the feature.

----

> right now ther's onClose but it runs before the animation is complete, causes issue when same state variable is used both as open prop and in the content

In #327 , you only leave a short sentence, it's hard for me to know what you want. For you, it only takes a short time to make the issue easier for others to understand. For me, I need to consider the feature you say and implement it. If you don't have time to edit an issue, I can only close it. (I hope you understand that.)

----

For this feature:

According to your description, the difference between `onClose` and `onClosed` is only `350ms` of animation time, or is there any other difference?
I don't quite understand what you mean by *used in the `open` prop*, is it possible that there are misunderstandings in the way you use them, with `state variable`, you can easily track the state of `useEffect`.

**Comment by bryanhpchiang** [comment]
> If you need to propose a feature, please give a detailed example and why you need it. To ensure that others understand your intentions, a picture, video, or online example is a good choice. 

This is why the "just a suggestion" box was checked -- not a detailed feature proposal (i.e. the first check box), just bringing up a common use case to ask about. Lots of other issues (resulting in some sort of change) that were similarly short.

> The reality is that you haven't even changed the Expected option, it's a default character.

I explained under Expected option, some people prefer using sentences rather than bullet points. Also added an example of what the API looks like, only takes a line because it's not too complex.

> In #327 , you only leave a short sentence, it's hard for me to know what you want. For you, it only takes a short time to make the issue easier for others to understand. For me, I need to consider the feature you say and implement it. If you don't have time to edit an issue, I can only close it. (I hope you understand that.)

Of course I have time to edit an issue...that's why I reopened an entirely new one. Takes less time for you (not me lol) to ask for clarification vs. closing the issue with an explanation + responding to a new one (not counting the feature development time as a maintainer).

For the actual issue - prob. not high priority, but consider the simple case (not tested)

```
const [error, setError] = useState ...
<Modal open={error}>
<Modal.Title>Error</Modal.Title>
<Modal.Content><Text>{error}</Text></Modal.Content>
</Modal>
```

Every millisecond matters to me - if you setError(null) the error disappears from the content before the animation disappears. Not a bug but just a nice to have since onAnimationComplete handlers are pretty common.

**Comment by unix** [comment]
I don't want to argue with you about these things, just tell you why close.
There are several simple solutions to your problem, you can choose one of them:
  - Manage one more `state` instead of treating the error message as a switch.
  - If you just want a single `state`, you can encapsulate `Modal` once and get your own error component, [I create an online example for your reference.](https://codesandbox.io/s/zeit-ui-error-modal-s8kfd)
  - Use the last rendered value as the `Modal` content, [here's an example to inspire you.](https://usehooks.com/usePrevious/)
