### ISSUE TITLE
Hard-coded background color value

### ISSUE THREAD

**Issue by firede** [zeit-ui/react#337]
# Bug report 🐞

## Version & Environment

  - `zeit-ui/react`: latest & rc

## Expection

`<Link block />` use custom theme colors.

## Actual results (or Errors)

<img width="216" alt="CleanShot 2020-07-19 at 17 52 33@2x" src="https://user-images.githubusercontent.com/157338/87872131-aa997200-c9e8-11ea-855e-5a61c1af70a6.png">

ref:
https://github.com/zeit-ui/react/blob/23baf4aaf57d7eaeed63a20b2b0c22edacee724f/components/link/link.tsx#L68

**Comment by unix** [comment]
Yes, this is intentional. `block` mode is a special style that doesn't exist in themes.
Of course, you can change it through `CSS`.

**Comment by unix** [comment]
closed. If you have any update, reopen it.
