### ISSUE TITLE
Type erros of  Button and Link components

### ISSUE THREAD

**Issue by unix** [zeit-ui/react#34]
# Bug report 🐞

Use these components with an error message:

```ts
const App = () => {
  return (
    <>
      <Button>My Button</Button>
      <Link>My Link</Link>
    </>
  );
};
```

### Hint Errors

```
This JSX tag's 'children' prop expects type 'never' which requires multiple children, but only a single child was provided.ts(2745)
```

**Comment by unix** [comment]
@ofekashery 
Could you fill in the details of the recurrence problem? (I can't reproduce this error in the test)

**Comment by ofekashery** [comment]
I just created a new typescript ``create-react-app`` project, then installed the package (from npm).
I see the error in my VS Code, not in the Terminal or something..
![image](https://user-images.githubusercontent.com/16443111/77835955-fb980880-7162-11ea-81e3-3a0b7b188ce3.png)

**Comment by unix** [comment]
Can you try this project: [react-ts-getting-started](https://github.com/zeit-ui/react-ts-getting-started)
It looks work normal. You can also try to modify the editor configuration on this basis, please let me know if you have any updates.

**Comment by ofekashery** [comment]
Really weird, I even reset the VSCode settings.
![image](https://user-images.githubusercontent.com/16443111/77836563-56802e80-7168-11ea-83c7-1872b7f11280.png)

**Comment by ofekashery** [comment]
@unix The issue is that we define properties that are also used by ``HTMLAttributes``.
For example, the ``type`` property/attribute is used for our Button component, but also part of the ``HTMLAttributes`` (for ``input``s).
I'm working on PR now.

**Comment by unix** [comment]
This issue may appear in multiple compoennts,  maybe `Partial<React.ButtonHTMLAttributes<any>>`  will solve the issue?
