### ISSUE TITLE
Support jump to bullets in docs page

### ISSUE THREAD

**Issue by yqrashawn** [zeit-ui/react#343]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

  - jump to `API` bullet in fieldset page when open this https://react.zeit-ui.co/en-us/components/fieldset#apis

**Comment by unix** [comment]
This function has encountered some problems, and I am still in the process of continuous research.

The main reason is that the current document samples are **lazy loading**, the `height` of the document page changes several times when it is first loaded (it depends on the network speed of the load). Now it seems that if we scroll to the anchor when first load the page, the change in `height` can actually reduce the user experience. 😢  

I'm trying some other ways around this question, but I don't have a good answer. If anyone has a better practice or opinion, please let me know.

**Comment by unix** [comment]
Closed.
This feature is not easy to implement at present, anyone who has a new idea, please reopen it.
