### ISSUE TITLE
Custom className for component Card does not work

### ISSUE THREAD

**Issue by appako** [zeit-ui/react#349]
# Bug report 🐞

## Version & Environment

  - Version of browser: Chrome 84
  - Version of `zeit-ui/react`: 1.8.0-canary.7

## Expection

In our [examples/custom-styles](https://github.com/zeit-ui/react/tree/master/examples/custom-styles):
I want to add custom class **.my-card** for the Card component, but it doesn't work, because the Card uses the tag style internally.

## Actual results (or Errors)

![image](https://user-images.githubusercontent.com/36507984/88464943-62d28900-cec7-11ea-859a-502347acf69b.png)

```

// home.jsx
<Card shadow style={{ width: '500px', margin: '100px auto' }} className="my-card>
      <Text className="my-text">Modern and minimalist React UI library.</Text>
      ....
</Card>

// style.css
.my-card {
    background-color: grey;
}
```

**Comment by unix** [comment]
Can it help you: #317 ？

**Comment by appako** [comment]
> Can it help you: #317 ？

I know several ways how to get around this :))) But I don’t want to do this, because I believe this is a bug and can be fixed.

**Comment by unix** [comment]
Well, there is no plan to change the style solution in the short term, or, do you have any new opinion?

**Comment by appako** [comment]
> Well, there is no plan to change the style solution in the short term, or, do you have any new opinion?

No, thanks for the quick answer, I understand you. You can close this issue.

**Comment by unix** [comment]
Sorry for not having a satisfactory solution, I'll keep looking into it, if I have a more elegant answer, I will remind you again.
