### ISSUE TITLE
Error on Modal.Action types

### ISSUE THREAD

**Issue by wcastand** [zeit-ui/react#350]
# Bug report 🐞

## Version & Environment

  - Version of vscode: 1.47.2
  - Version of `zeit-ui/react`: ^1.8.0-canary.7

## Expection

i expect no error when i copy/paste the code from the examples

## Actual results (or Errors)

I got a typescript error on the example for Modal:

```jsx
    <Modal open={state} onClose={closeHandler}>
    <Modal.Title>Modal</Modal.Title>
    <Modal.Subtitle>This is a modal</Modal.Subtitle>
    <Modal.Content>
      <p>Some content contained within the modal.</p>
    </Modal.Content>
    <Modal.Action passive onClick={() => setState(false)}>Cancel</Modal.Action>
    <Modal.Action>Submit</Modal.Action>
  </Modal>
```

the error i get in vscode and the browser: 
<img width="863" alt="Screenshot 2020-07-27 at 11 54 35" src="https://user-images.githubusercontent.com/2178244/88529463-51d96300-d000-11ea-98b1-34a7d4260cd0.png">

I'm not sure why but `Mocal.Action` seems to not have the proper Props passed in the types.

**Comment by unix** [comment]
Thanks for the bug report, version `v1.8.0-canary.8` is now available.
Any update, please reply to me.

**Comment by wcastand** [comment]
no more error in vscode with the new version. Thanks ! i think we can close this one :)
