### ISSUE TITLE
Make the modal accessible

### ISSUE THREAD

**Issue by Fumler** [zeit-ui/react#352]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

  - Currently the modal component is not accessible, meaning if you use the keyboard to navigate (e.g. with `tab`) it will navigate the page in the background instead.
  - The modal component should capture keyboard focus and have proper aria attributes.

**Comment by nonissue** [comment]
If I may add: Pressing escape should close the modal. I think this follows accessibility conventions, and I found [this](https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html) guideline. 

I actually might be able to take this on, just familiarizing myself with the code base. If I feel comfortable with it, I will follow up!

**Comment by unix** [comment]
@nonissue Of course, I quite agree with you. 
I'll add this feature next, but not in this pull request. (my current work is to add test cases for #354)

**Comment by unix** [comment]
The pre-release version `v1.8.0-canary.9` is out now.
