### ISSUE TITLE
Import single component, no typing availlable

### ISSUE THREAD

**Issue by hoetmaaiers** [zeit-ui/react#358]
# Bug report 🐞

When importing a single component as described in the [installation guide](https://react.zeit-ui.co/en-us/guide/installation). No typing is available.

## Version & Environment

  - Version of browser: Typescript
  - Version of `zeit-ui/react`: @1.8.0-canary.8

## Expection

I expect to have access to the same Typescript definition when importing a single component.

## Actual results (or Errors)

I got an error:

```
Could not find a declaration file for module '@zeit-ui/react/esm/tooltip'. '/node_modules/@zeit-ui/react/esm/tooltip/index.js' implicitly has an 'any' type.
  Try `npm install @types/zeit-ui__react` if it exists or add a new declaration (.d.ts) file containing `declare module '@zeit-ui/react/esm/tooltip';`

```

**Comment by unix** [comment]
I follow the example of [examples/tree-shaking-create-react-app](https://github.com/zeit-ui/react/blob/master/examples/tree-shaking-create-react-app/README.md) to create a project using `TypeScript`, it seems to work well, can you share your project?

**Comment by hoetmaaiers** [comment]
Yes, I created this simple CRA app with a button imported via ESM.
The problem lies in this line: https://github.com/hoetmaaiers/zeit-ui-esm-types/blob/master/src/App.tsx#L2

**Comment by unix** [comment]
As explained in the example project, you need to use babel plugin to complete the `tree-shaking`, your `import` statement is no different than usual, in other words, this code is unnecessary:

```jsx
import Button from '@zeit-ui/react/esm/button'
```

Replace it with a generic `import` statement:

```jsx
import { Button } from '@zeit-ui/react'
```

I created a pull request for your project, this should solve the problem: [zeit-ui-esm-types/pull/1](https://github.com/hoetmaaiers/zeit-ui-esm-types/pull/1).

**Comment by hoetmaaiers** [comment]
Thank you for the PR but this solution was no problem. I didn't consider tree-shaking so I thought my only option to only include the `Button` was to import is a single module via ESM. Not the case then.

Thank you for thinking along.
