### ISSUE TITLE
(docs) Switch themes error

### ISSUE THREAD

**Issue by nocategory** [zeit-ui/react#39]
# About `docs`

The example code at the first section (Switch themes) at [https://react.zeit-ui.co/docs/customization/themes](url) does not work properly, at least on Next.js  9.2.2, since:

1. The hooks need to be inside the function component, and not outside;
2. `useTheme()` doesn't seem to be very needed, since the current theme type will be stored on the `type` state variable?
3. At `const switchThemes = () => () =>` the extra set of `=> ()` isn't needed;
4. At `<ZEITUIProvider theme={{ type }}>` the theme attribute actually takes in a value of type ThemeParam, which is an array of objects, where there is a "type" property. Therefore I replaced the above for `<ZEITUIProvider theme={{ type: typevariable }}>`;

As an example, this is my code currently (which works):
```js
const App = () => {
  const [themeType, setThemeType] = useState('dark')
  const switchThemes = () => {
    let nextTheme = themeType === 'dark' ? 'light' : 'dark'
    setThemeType(nextTheme)
  }
  return (
    <ZEITUIProvider theme={{ type: themeType }}>
      <CSSBaseline />
      <MyApp pressAction={switchThemes} />
    </ZEITUIProvider>
  )
}
```
I can make a commit with the updated code for the docs in case this is confirmed, or maybe you'll want to change some things on the code

**Comment by unix** [comment]
Yes, you are right. I'm sorry, I wrote this document in such a hurry that I left a lot of mistakes. Thank your for your work, you  can create PR at any time.

A digression, can we write like this (the state of `nextTheme` does not need to be tracked):

```
const switchThemes = () => {
  setThemeType(lastType => lastType === 'dark' ? 'light' : 'dark')
}
```
