### ISSUE TITLE
Bundle sizes would be smaller if you set `styled-jsx` to be external

### ISSUE THREAD

**Issue by itshaydendev** [zeit-ui/react#47]
If you added it as a peerDependency, and then told Rollup to mark it as external (and thus not need to bundle it), you'd decrease your bundle size quite a lot.

**Comment by unix** [comment]
Thanks for the advice. I've thought about it, and there are several main reasons for bundle in `styled-jsx`:

  - Reduce config items for user (At present, `styled-jsx` must be configured with `Babel`)
  - Simplify project start-up complexity
  - No burden of thinking when user use other styles solutions

It's a trade-off, of course not the best solution, but the current bundle solution improves the developer experience, I think that's very important. These advantages are more important than [30KB size (uncompressed)](https://cdn.unix.bio/?q=styled-jsx&npm=1).

Even if the user configures package `styled-jsx` manually, when a user's web application is published, **package `styled-jsx` will eventually be included**. The `peerDependency` only makes our package look small, but it's not really small.
