### ISSUE TITLE
Optimize the style of documents on the mobile

### ISSUE THREAD

**Issue by unix** [zeit-ui/react#6]
# Feature request 🚀

### Expected:
  - All documents adapt to mobile

**Comment by itshaydendev** [comment]
![image](https://user-images.githubusercontent.com/22327045/77230917-a884eb00-6b8f-11ea-9a56-e2e3b514fc54.png)
![image](https://user-images.githubusercontent.com/22327045/77230922-ade23580-6b8f-11ea-8f03-96f77c954147.png)

Here are some screenshots of how it looks on mobile (thanks to Edge's responsive devtools)

**Comment by unix** [comment]
Thanks 😃, I will refer to this design & layout.

**Comment by itshaydendev** [comment]
:)
