### ISSUE TITLE
`next/link` to work with `Button`

### ISSUE THREAD

**Issue by datnq** [zeit-ui/react#66]
# Bug report 🐞

## Expection
I used `next/link` to wrap UI button and get `forwardRef` error:

```jsx
<NextLink href='/write'>
  <Button ghost auto>
    <Add /> Write a story
  </Button>
</NextLink>
```
## Actual results (or Errors)
```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
```

**Comment by unix** [comment]
Yes, it's reasonable.
The `NextLink` use `refs` from anchor element, but a functional component cannot be given `refs`.

We provide `forwardRef` functional component `Link` to solve the problem:

```jsx
import NextLink from 'next/link'
import { Link } from '@zeit-ui/react'

() => (
  <NextLink href="#">
    <Link>Hyperlink</Link>
  </NextLink>
)
```

If you want to use `Button` or other components (add `pure` property to remove icon):

```jsx
import NextLink from 'next/link'
import { Link, Button } from '@zeit-ui/react'

() => (
  <NextLink href="#">
    <Link pure>
      <Button>Write a story</Button>
    </Link>
  </NextLink>
)
```

**Comment by datnq** [comment]
It works! Thanks.
