### ISSUE TITLE
Link color not present on dark mode

### ISSUE THREAD

**Issue by laurosilvacom** [zeit-ui/react#83]
## Version & Environment

```
"@zeit-ui/react": "^0.0.1-beta.20",
```

## Expectation

Link color should be blue when `theme.type === 'dark'`. 

## Actual results

All Links have a `color: white;` when `theme.type === 'dark'`. 

The only global styles set are through `<CSSBaseline />`. 

![Apr-11-2020 00-04-14](https://user-images.githubusercontent.com/57044804/79037670-0a7db280-7b88-11ea-8aff-3917e458a05e.gif)

**Comment by unix** [comment]
Yes, this is design style... refer to [design](https://zeit.co/design/link).

I think the design of links affects readability, but I also want to fully express the original design style.
As a moderate solution, we change the color of `Link` with attribute `color` in dark mode?

I want to hear from you.

**Comment by laurosilvacom** [comment]
I didn't realized that it was part of the original design. Props on following the original design! 😄 

Having the ability to change the attribute `color` in the dark mode would be helpful. Is that something that's possible with the current component. Or is this something that needs to be built in?

**Comment by unix** [comment]
Wait for this PR to merge #89 , and the new beta version will be released.
