### ISSUE TITLE
Slow CSS Start Up

### ISSUE THREAD

**Issue by wintkhantlin** [zeit-ui/react#845]
# Bug report 🐞

## Version & Environment

  - Version of browser `Chrome Version 115.0.5790.110 (Official Build) (64-bit)`
  - Version of `geist-ui/core` : `^2.3.8`

## Expected Behaviour

The behavior I expect is load with full styled components

## Actual results (or Errors)

I got an error:
Every time I open a link in the development environment or production, the built-in components with no style are loaded first, and after that, they change to dark mode. I think the styles should be loaded together

Here is the website
https://powefu.vercel.app

**Comment by wintkhantlin** [comment]
![image](https://github.com/geist-org/geist-ui/assets/96770798/24076fd6-c5a3-4bc1-a241-9c94aa9b1f22)

**Comment by diploidal** [comment]
Please provide link to code base (if available). It would make debugging much faster. 

For now You could try doing something like this in Your main App component: 

```jsx
function App({
  Component,
  pageProps,
}) {
  const [
    isMounted,
    setItMounted,
  ] = useState(false);

  if(!isMounted) return null;

  useEffect(() => {
    setItMounted(true);
  }, []);

  return (
    <ThemeProvider>
      <GeistProvider themeType={themeType}>
        <CssBaseline />
          {
           isMounted && (
            <Component
              {...pageProps}
            />
          )}
      </GeistProvider>
    </ThemeProvider>
  );
}

export default App;
```

This `useState` combined with `useEffect` and conditional rendering should prevent from style/theme flickering but I think You would have to additionally implement `themeType` for `GeistProvider`. 


Although this "hack" should not be use at all. There may be some problem with how You've implemented `Geist ui` itself but without source code it is impossible to assume things. 😃

**Comment by kaitoukid-1412** [comment]
Hi @happer64bit ,

- You need config `styles` in `_document.js` when `Server Render`

```
https://geist-ui.dev/en-us/guide/server-render
```

![image](https://github.com/geist-org/geist-ui/assets/15698245/5dd0f9ce-a90f-43d5-8383-14889b6e3663)

- and make sure `styles` are loaded

![image](https://github.com/geist-org/geist-ui/assets/15698245/e4677b8a-fcef-40c6-b5eb-3fa332a1c849)

![image](https://github.com/geist-org/geist-ui/assets/15698245/5cd5aa18-1be9-46c7-b609-04857b7fe8e0)

**Comment by ofekashery** [comment]
Hi @happer64bit! As mentioned by the community, please make sure you followed the [server rendering guide](https://geist-ui.dev/en-us/guide/server-render), or add a link to a minimal code that reproduces this issue.
