### ISSUE TITLE
Limit the height of the Select Component

### ISSUE THREAD

**Issue by ofekashery** [zeit-ui/react#88]
# About `styles` 🛠️

![image](https://user-images.githubusercontent.com/16443111/79052885-1cbc2700-7c42-11ea-8487-e98d10bfdfcd.png)

### It should be like this
![image](https://user-images.githubusercontent.com/16443111/79053071-24c89680-7c43-11ea-88ef-facd38810fa9.png)

**Comment by unix** [comment]
Good advice, thanks much!
I'll fix it ASAP.
