### ISSUE TITLE
Ellipsis Support for Multiline Text

### ISSUE THREAD

**Issue by kckusal** [zeit-ui/react#97]
# Feature request 🚀

### Expected:
  - A component that takes text spanning over multiple lines, clips the overflowing text (i.e. parts that do not fit in the provided number of lines) out, and adds an ellipsis (...) at the end (with optionally an _expand_ text button to see the complete text).

### Examples:
This is available in ant design Paragraph component under Typography.
[https://ant.design/components/typography/#components-typography-demo-ellipsis](https://ant.design/components/typography/#components-typography-demo-ellipsis)

**P.S.** Absolutely loved the simplicity of the components and their designs.

**Comment by unix** [comment]
The `ellipsis` props constrains the `children` of the component to be plain text only. And  this kind of expression has never appeared in the design of ZEIT. So, I think the feature of `text ellipsis` is unnecessary, at least for the moment. (Unless more people request this feature, or we found reasonable guidelines on ZEIT design.)

Thank you very much for your advice.
